#!/bin/sh

printf "Start commitment check...\n"

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
    exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    # skip vendor
    if [[ $FILE == "vendor"* ]];then
        continue
    fi

    # goimports
    goimports -w $FILE
    if [[ $? != 0 ]]; then
        PASS=false
    fi

    # golint
    golint "-set_exit_status" $FILE
    if [[ $? == 1 ]]; then
        PASS=false
    fi

    # go tool vet
    go vet $FILE
    if [[ $? != 0 ]]; then
        PASS=false
    fi

  # format
    UNFORMATTED=$(gofmt -l $FILE)
    if [[ "$UNFORMATTED" != "" ]];then
        gofmt -w $PWD/$UNFORMATTED
        if [[ $? != 0 ]]; then
            PASS=false
        fi
    fi

    # add changed files
    git add $FILE

done

if ! $PASS; then
    printf "\033[31m COMMIT FAILED \033[0m\n"
    exit 1
else
    printf "\033[32m COMMIT SUCCEEDED \033[0m\n"
fi

exit 0